### ISSUE TITLE
Question about Loose Track Training Guideline

### ISSUE THREAD

**Issue by Zephyr1022** [babylm/evaluation-pipeline#2]
According to the guidelines, it said "training on additional text is allowed without limits if that text is generated by a model trained following the above restrictions."  I'm curious if I can generate text using the hard prompt template and then combine the prompt and generated output to use as input for training.

**Comment by aaronmueller** [comment]
Do you mean using a template-based approach to modify the training data we provide, and then adding that to the training set? Depending on the templating procedure, that would probably be fine. Generally, deterministic or heuristic-based approaches for augmenting the data are acceptable for the loose track, so long as the augmentation method doesn't take in any outside data or expert annotations.

**Comment by Zephyr1022** [comment]
Would human feedback be considered as expert annotations?

**Comment by aaronmueller** [comment]
It depends on how the human feedback is presented: if it's textual feedback, then this would count toward the 100M word limit in the loose track. If it's number ratings for model outputs, this should be fine. Both of these would only be allowed in the loose track.

Thanks for the questions!

**Comment by jumelet** [comment]
@aaronmueller , are you saying that no data augmentation whatsoever is allowed in the strict tracks? That surprises me, I don't see why modifying the data (without being dependent on outside sources) would not full under the strict regime, as long as we do not add additional data coming from other data sources.

**Comment by aaronmueller** [comment]
Hi @jumelet! We answered a similar question in the slack, but posting the answer here as well.

If you use only trivial modifications to the existing data that don't rely on human annotations or complex algorithms/heuristics, this would be allowed in the strict track. Something akin to training an LM on the strict data and then using this to generate more data would be allowed, for example, but nothing involving human expertise or non-trivial modifications to the dataset. And, of course, no external data.
