### ISSUE TITLE
TypeError: an integer is required (got type NoneType)

### ISSUE THREAD

**Issue by Zephyr1022** [babylm/evaluation-pipeline#3]
I encountered an error shown as follows while testing the code on the 'decoder' model. Could you provide some suggestions on how to debug the code?

 Running all `loglikelihood` requests
  0%|                                                                                                                          | 0/3911 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/BabyLM/evaluation-pipeline/babylm_eval.py", line 63, in <module>
    accuracies[task_title] = accuracy_on_task(task, eval_model, template,
  File "/BabyLM/evaluation-pipeline/babylm_eval.py", line 17, in accuracy_on_task
    results = lm_eval.evaluate(model=eval_model, tasks=eval_task, seed=12, num_fewshot=num_fewshot)
  File "/BabyLM/evaluation-pipeline/lm_eval/evaluator.py", line 220, in evaluate
    resps = getattr(model, reqtype)([req.args for req in reqs])
  File "/BabyLM/evaluation-pipeline/lm_eval/api/model.py", line 179, in loglikelihood
    return self._loglikelihood_tokens(new_requests)
  File "/BabyLM/evaluation-pipeline/lm_eval/api/model.py", line 283, in _loglikelihood_tokens
    input = torch.tensor(
TypeError: an integer is required (got type NoneType)

**Comment by aaronmueller** [comment]
Can you provide some details about the model architecture—e.g., is it based on GPT or OPT? Which class would it belong to in HuggingFace (e.g., GPT2Model)?

Another possibility is that the tokenizer isn't being loaded properly. Are the tokenizer config files included in the same directory as the model?

**Comment by Zephyr1022** [comment]
Thank you. I figure out the error is from my tokenizer.

**Comment by Zephyr1022** [comment]
I think the issue may be come from my tokenizer. Would it be possible to use a pre-trained tokenizer instead? Thank you.
