### ISSUE TITLE
`pip install -e ".[dev]"` hangs

### ISSUE THREAD

**Issue by mhrmm** [babylm/evaluation-pipeline#4]
I'm having an issue getting the evaluation pipeline set up. I've tried running:

    pip install -e ".[dev]"

locally, and it hangs after the message "Branch 'eval-hackathon' set up to track remote branch 'eval-hackathon' from 'origin'." The same issue seems to be happening in the provided Colab.

<img width="1321" alt="Screen Shot 2023-04-01 at 10 15 30 AM" src="https://user-images.githubusercontent.com/1376035/229294489-2c34c45e-2d28-4da5-9f31-332d69623245.png">

Perhaps it's a temporary issue (or operator error), but figured I'd bring it to your attention.

**Comment by aaronmueller** [comment]
I could replicate the issue on Colab, but local installation worked for me. Could you provide some detail on your python and pip versions?

In a future commit, I'm planning to remove reliance on `promptsource` altogether. For now, though, I'm working on a `colab` branch that skirts this. Will update this thread when that's ready!

**Comment by mhrmm** [comment]
Sure! I'm using Python 3.9.16 and pip 23.0.1 on Ubuntu 20.04 LTS.

**Comment by asparius** [comment]
I am experiencing the same problem.

**Comment by aaronmueller** [comment]
Mind giving the Colab a try now?

I made a `colab` branch and changed the dependencies to not rely on the GitHub version of `promptsource`. Installation finished, and zero-shot eval and fine-tuning worked!

I still wasn't able to replicate the issue when installing locally `main` branch using `pip install -e ".[dev]"`, even when using those python and pip versions. Not sure what the issue would be, but I'll work on making `main` not rely on promptsource this week.

**Comment by asparius** [comment]
Nope, it does not seem to work in this [colab](https://colab.research.google.com/drive/1uqwuUexAy5LqL7DJiE9mzHm5U568a8fP?usp=sharing)

**Comment by aaronmueller** [comment]
@asparius Use `pip install -e ".[colab]"` followed by `pip install promptsource==0.2.3` when working on the Colab, as is now used [on the official Colab link](https://colab.research.google.com/drive/1HX2D3wztO81tKcqCeV_ecRcEUseBVuTc?usp=sharing).

`pip install -e ".[dev]"` still hangs on Colab for now.

**Comment by asparius** [comment]
The official colab link guideline works locally as well. Thank you
