### ISSUE TITLE
Fine-tuning script missing "transformers_modified"

### ISSUE THREAD

**Issue by Leukas** [babylm/evaluation-pipeline#6]
The finetune_classification.py script currently fails when trying to fine-tune a T5 model because of line 419:
`from transformers_modified.t5 import T5ForSequenceClassification`

It fails with:
`ModuleNotFoundError: No module named 'transformers_modified'`

I don't see any other instances of 'transformers_modified' in the repo.

**Comment by aaronmueller** [comment]
Whoops, thanks for catching this! This got lost when I ported over the files from a previous development repo. Try now.
