### ISSUE TITLE
Typo in baseline results ?

### ISSUE THREAD

**Issue by scfrank** [babylm/evaluation-pipeline#7]
ROBERTa's performance on strict/BLIMP/Anaphor Agr is very low (17.4) - maybe is this a typo for 71.4?

**Comment by YovaKem** [comment]
Another odd thing about the baseline results: the performance of T5-base (61.2%) in the strict-small track on CoLa beats the actual [T5-Base model](https://arxiv.org/pdf/1910.10683v3.pdf) (51.1%). The CoLa results are generally very high. Could that really be?

**Comment by aaronmueller** [comment]
@scfrank: Thanks for catching this! This was indeed a mistake. The actual score is much higher :) we went ahead and checked the rest of the scores for this model as well.

@YovaKem: There are multiple differences that contribute to this discrepancy. First and biggest difference: we're reporting accuracies (range 0 to 1), not Matthews correlations (range -1 to 1), and accuracies will be much higher. For reference, the accuracy on CoLA for T5-base on our filtered dataset is closer to 81.8 (compared to our baseline's 61.2), and the Matthews correlation for T5-base is 55.1 (compared to our baseline's 7.0). Lots of room for improvement!

Second: we filter the CoLA dataset to better suit the vocabulary of our strict-small dataset, so numbers we report will not be exactly comparable to the numbers reported in prior work which uses the full dataset.

Third: we use a different method to perform classification with T5. While the T5 paper _generated_ single-word labels, we instead use the [EncT5 method](https://arxiv.org/abs/2110.08426), where a classification head is appended to the encoder. This method was found to be better for discriminative tasks at smaller parameterizations, and it helps us get around the issue of our label words (like "acceptable" or "unacceptable") not appearing in the strict-small vocabulary very often, or at imbalanced frequencies.
