### ISSUE TITLE
Possible bug in evaluation script

### ISSUE THREAD

**Issue by YovaKem** [babylm/evaluation-pipeline#9]
When evaluating e.g. for SST2, the trainer seems to incorrectly select the best model checkpoint to be from step 1000 when the eval accuracy clearly continues to improve in subsequent steps. This results in a lower final accuracy being reported at the end than the actual one the model achieves. 

Below is the output of `trainer.log_history` and `trainer.best_model_checkpoint`
```
log_history=[
{'eval_loss': 0.43397894501686096, 'eval_accuracy': 0.8090550899505615, 'eval_f1': 0.8101761252446184, 'eval_runtime': 0.3408, 'eval_samples_per_second': 1490.483, 'eval_steps_per_second': 187.777, 'epoch': 0.25, 'step': 200}, 
{'eval_loss': 0.40459370613098145, 'eval_accuracy': 0.8307086825370789, 'eval_f1': 0.833976833976834, 'eval_runtime': 0.3147, 'eval_samples_per_second': 1614.033, 'eval_steps_per_second': 203.343, 'epoch': 0.51, 'step': 400},
{'eval_loss': 0.3854110538959503, 'eval_accuracy': 0.8444882035255432, 'eval_f1': 0.8483685220729367, 'eval_runtime': 0.3154, 'eval_samples_per_second': 1610.677, 'eval_steps_per_second': 202.92, 'epoch': 0.76, 'step': 600}, 
{'eval_loss': 0.36048293113708496, 'eval_accuracy': 0.8602362275123596, 'eval_f1': 0.8599605522682446, 'eval_runtime': 0.3237, 'eval_samples_per_second': 1569.322, 'eval_steps_per_second': 197.71, 'epoch': 1.01, 'step': 800},
{'eval_loss': 0.36621662974357605, 'eval_accuracy': 0.8582677245140076, 'eval_f1': 0.855421686746988, 'eval_runtime': 0.3169, 'eval_samples_per_second': 1603.248, 'eval_steps_per_second': 201.984, 'epoch': 1.27, 'step': 1000}, 
{'eval_loss': 0.36977794766426086, 'eval_accuracy': 0.8622047305107117, 'eval_f1': 0.8594377510040161, 'eval_runtime': 0.3405, 'eval_samples_per_second': 1491.796, 'eval_steps_per_second': 187.943, 'epoch': 1.52, 'step': 1200}, 
{'eval_loss': 0.4045640230178833, 'eval_accuracy': 0.8622047305107117, 'eval_f1': 0.866412213740458, 'eval_runtime': 0.3215, 'eval_samples_per_second': 1580.063, 'eval_steps_per_second': 199.063, 'epoch': 1.77, 'step': 1400}, 
{'eval_loss': 0.3876116871833801, 'eval_accuracy': 0.8681102395057678, 'eval_f1': 0.8667992047713717, 'eval_runtime': 0.3189, 'eval_samples_per_second': 1592.866, 'eval_steps_per_second': 200.676, 'epoch': 2.03, 'step': 1600},
{'eval_loss': 0.4254477918148041, 'eval_accuracy': 0.8543307185173035, 'eval_f1': 0.8587786259541984, 'eval_runtime': 0.3182, 'eval_samples_per_second': 1596.405, 'eval_steps_per_second': 201.122, 'epoch': 2.28, 'step': 1800}...
]

best_model_checkpoint='.../finetune/sst2/checkpoint-1000'
```

**Comment by YovaKem** [comment]
On a related note, even though training is configured to run for 10 epochs, it stops after 3000 steps which amounts to 3.8 epochs. There is no apparent reason why that should be considering that the eval accuracy steadily improves up until that point.

**Comment by aaronmueller** [comment]
Looks like it's choosing the best model based on loss, rather than the accuracy/f1 metrics. It also looks like the `save_steps` argument defaults to 500 rather than the `eval_every` default of 200, which is why it doesn't use step 800; thank you for catching this!

This also explains why it stops at step 3000. It thinks that step 1000 is best because it achieves the lowest loss of any step thus far (out of the steps that are a multiple of 500, I think). Because the patience is 10, it will stop after (10*200=)2000 steps if no improvement over the best loss is found.

Will update once these are fixed. Thanks!

**Comment by YovaKem** [comment]
Okay, you're right. I added prefix "eval_" to the `metric_for_best_model` arguments (don't know why that would be necessary but it seems to help) and explicitly set `save_steps = data_args.eval_every`, and things look alright now. 

Do the baseline results need to be updated accordingly?

**Comment by YovaKem** [comment]
Hi, is there any progress on solving this issue? Thanks.

**Comment by aaronmueller** [comment]
This should be resolved. Let me know if you run into any other issues now.
